version: "3.9"

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    container_name: testbooks-db
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT-5432}:5432

volumes:
  postgres_data:
